apiVersion: kalavai.net/v1
kind: ServerWorkerSet
metadata:
  name: scale-llamacpp
  namespace: default
spec:
  replicas: 2             
  workersPerInstance: 1   
  labels:
    custom-label: "value"
  serverPolicy:
  - event: PodFailed
    action: RestartInstance
  - event: OOMKilled
    action: RestartInstance
  - event: PodEvicted
    action: RestartInstance
  - event: Unknown
    action: RestartInstance
  workerPolicy:
  - event: PodFailed
    action: ReplacePod
  - event: OOMKilled
    action: ReplacePod
  - event: OOMKilled
    action: ReplacePod
  - event: PodEvicted
    action: ReplacePod
  - event: Unknown
    action: ReplacePod
  serverService:
    port: 8080           
    targetPort: 8080     
    stickySession: true  
    stickySessionTimeoutSeconds: 10800  
    serviceType: NodePort  
  autoScaling:
    enabled: false       
    hosts:
      - llamacpp.spaces.kalavai.net       
    pathPrefixes:
      - "/"              
    replicas:
      min: 0            
      max: 2
    scaledownPeriod: 300
    scalingMetric:
      requestRate:
        granularity: 1s
        targetValue: 1
        window: 1m
      # concurrency:
      #   targetValue: 10
  serverPodSpec:
    runtimeClassName: nvidia
    nodeSelector:
      kalavai/region: uspor01
    containers:
      - name: server
        image: ghcr.io/kalavai-net/llamacpp-cuda:b8941-1
        command: 
        - bash
        - -c
        - |
          echo "Starting server..."
          echo "SERVER_ADDRESS: $SERVER_ADDRESS"
          echo "WORKERS_ADDRESSES: $WORKERS_ADDRESSES"
          # run model server
          export WORKERS=$(/workspace/get_workers_address.sh --rpc_port=50052 --rpc_servers="${WORKERS_ADDRESSES}")
          /workspace/run_api_server.sh \
            --repo_id=unsloth/gemma-3-4b-it-GGUF \
            --quant=Q4_K_M \
            --port=8080 \
            --rpc_servers=$WORKERS \
            --extra='--cache-type-k q4_0 --cache-type-v q4_0'
        env:
        - name: HF_TOKEN
          value: ""
        ports:
          - containerPort: 8080
        # helps scaler detect when server is ready
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            nvidia.com/gpu: "1"
            cpu: 4
            memory: 8Gi
            ephemeral-storage: 10Gi
          limits:
            nvidia.com/gpu: "1"
            cpu: 4
            memory: 8Gi
            ephemeral-storage: 10Gi
  workerPodSpec:
    runtimeClassName: nvidia
    nodeSelector:
      kalavai/region: uspor01
    containers:
      - name: worker
        image: ghcr.io/kalavai-net/llamacpp-cuda:b8941-1
        # SERVER_ADDRESS points to THIS instance's server (not shared across instances).
        command:
          - bash
          - -c
          - |
            echo "Starting worker..."
            /workspace/run_rpc_worker.sh --rpc_port=50052
        resources:
          requests:
            nvidia.com/gpu: "1"
            cpu: 4
            memory: 8Gi
            ephemeral-storage: 10Gi
          limits:
            nvidia.com/gpu: "1"
            cpu: 4
            memory: 8Gi
            ephemeral-storage: 10Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scale-llamacpp-ingress
spec:
  ingressClassName: traefik
  rules:
  - host: llamacpp.spaces.kalavai.net
    http:
      paths:
      - backend:
          service:
            name: scale-llamacpp-service
            port:
              number: 8080 # match internal port
        path: /
        pathType: Prefix