kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: my-llm-job-scaler
spec:
  hosts:
    - myhost.com # matches the "host" in the request to the service at scaleTargetRef (if using ingress, matches the host field)
  pathPrefixes:
    - /
  scaleTargetRef:
    name: my-llm-job
    kind: ServerWorkerSet
    apiVersion: kalavai.net/v1
    service: my-llm-job-service
    port: 8080
  replicas:
    min: 0
    max: 3
  scaledownPeriod: 30
  scalingMetric:
    requestRate:
      granularity: 1s
      targetValue: 1
      window: 1m